spring:
  datasource:
    url: ${ODB_SOURCE}
    username: ${ODB_NAME}
    password: ${ODB_OFFICIAL_DB}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
